#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void vt_obsw_pulse_deliver 
    (__po_hi_request_t* request);

void* vt_obsw_pulse_job (void);

void vt_obsw_takeoff_deliver 
    (__po_hi_request_t* request);

void* vt_obsw_takeoff_job (void);

void vt_ground_height_deliver 
    (__po_hi_request_t* request);

void* vt_ground_height_job (void);

void vt_ground_gui_polling_ground_deliver 
    (__po_hi_request_t* request);

void* vt_ground_gui_polling_ground_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
