#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"vt_obsw_takeoff_global_inport_artificial_takeoff","vt_obsw_takeoff_global_outport_getheight_vt","vt_obsw_pulse_global_outport_getheight_vt","vt_ground_getheight_global_inport_artificial_getheight","vt_ground_getheight_global_outport_takeoff_vt","vt_ground_gui_polling_ground_global_outport_takeoff_vt"};

