#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void vt_supervisor_pulse_deliver 
    (__po_hi_request_t* request);

void* vt_supervisor_pulse_job (void);

void vt_supervisor_takeoff_deliver 
    (__po_hi_request_t* request);

void* vt_supervisor_takeoff_job (void);

void vt_gcs_sensordata_deliver 
    (__po_hi_request_t* request);

void* vt_gcs_sensordata_job (void);

void vt_gcs_gui_polling_gcs_deliver 
    (__po_hi_request_t* request);

void* vt_gcs_gui_polling_gcs_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
