#ifndef __PRINTTYPES_H__
#define __PRINTTYPES_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintT_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintMyEnum(const char *paramName, const asn1SccMyEnum *pData);
void PrintMyChoice(const char *paramName, const asn1SccMyChoice *pData);
void PrintMyStates(const char *paramName, const asn1SccMyStates *pData);
void PrintT_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintMyReal(const char *paramName, const asn1SccMyReal *pData);
void PrintMyBool(const char *paramName, const asn1SccMyBool *pData);
void PrintMyTrajectory(const char *paramName, const asn1SccMyTrajectory *pData);
void PrintMyOctStr(const char *paramName, const asn1SccMyOctStr *pData);
void PrintT_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintMySeqOf(const char *paramName, const asn1SccMySeqOf *pData);
void PrintMyPWM(const char *paramName, const asn1SccMyPWM *pData);
void PrintT_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintMyInteger(const char *paramName, const asn1SccMyInteger *pData);
void PrintT_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintMySeq(const char *paramName, const asn1SccMySeq *pData);

#ifdef __cplusplus
}
#endif

#endif
