#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define __PO_HI_MY_NODE x86_partition_k

#define __po_hi_vt_obsw_pulse_nb_ports 2

#define __po_hi_vt_obsw_start_work_nb_ports 3

#define __po_hi_vt_ground_thrust_update_nb_ports 2

#define __po_hi_vt_ground_dheight_nb_ports 2

#define __po_hi_vt_ground_gui_polling_ground_nb_ports 1

/*  For each node in the distributed application add an enumerator*/

typedef enum
{
  x86_partition_k = 0
} __po_hi_node_t;

typedef enum
{
  invalid_protocol = -1
} __po_hi_protocol_t;

/*  For each thread in the distributed application nodes, add an enumerator*/

typedef enum
{
  x86_partition_vt_obsw_pulse_k_entity = 0,
  x86_partition_vt_obsw_start_work_k_entity = 1,
  x86_partition_vt_ground_thrust_update_k_entity = 2,
  x86_partition_vt_ground_dheight_k_entity = 3,
  x86_partition_vt_ground_gui_polling_ground_k_entity = 4,
  invalid_entity = -1
} __po_hi_entity_t;

typedef enum
{
  x86_partition_vt_obsw_pulse_k = 0,
  x86_partition_vt_obsw_start_work_k = 1,
  x86_partition_vt_ground_thrust_update_k = 2,
  x86_partition_vt_ground_dheight_k = 3,
  x86_partition_vt_ground_gui_polling_ground_k = 4,
  invalid_task_id = -1
} __po_hi_task_id;

typedef enum
{
  invalid_device_id = -1
} __po_hi_device_id;

typedef enum
{
  invalid_bus_id = -1
} __po_hi_bus_id;

#define __PO_HI_NB_TASKS 5

#define __PO_HI_TASKS_STACK 250000

#define __PO_HI_NB_PROTECTED 2

#define __PO_HI_NB_NODES 1

#define __PO_HI_NB_ENTITIES 5

#define __PO_HI_NB_PORTS 10

typedef enum
{
  vt_obsw_pulse_global_outport_thrust_update_vt = 0,
  vt_obsw_pulse_global_outport_dheight_vt = 1,
  vt_obsw_start_work_global_inport_artificial_start_work = 2,
  vt_obsw_start_work_global_outport_thrust_update_vt = 3,
  vt_obsw_start_work_global_outport_dheight_vt = 4,
  vt_ground_thrust_update_global_inport_artificial_thrust_update = 5,
  vt_ground_thrust_update_global_outport_start_work_vt = 6,
  vt_ground_dheight_global_inport_artificial_dheight = 7,
  vt_ground_dheight_global_outport_start_work_vt = 8,
  vt_ground_gui_polling_ground_global_outport_start_work_vt = 9,
  invalid_port_t = -1,
  constant_out_identifier = 11
} __po_hi_port_t;

typedef enum
{
  vt_obsw_pulse_local_outport_thrust_update_vt = 0,
  vt_obsw_pulse_local_outport_dheight_vt = 1,
  vt_obsw_start_work_local_inport_artificial_start_work = 0,
  vt_obsw_start_work_local_outport_thrust_update_vt = 1,
  vt_obsw_start_work_local_outport_dheight_vt = 2,
  vt_ground_thrust_update_local_inport_artificial_thrust_update = 0,
  vt_ground_thrust_update_local_outport_start_work_vt = 1,
  vt_ground_dheight_local_inport_artificial_dheight = 0,
  vt_ground_dheight_local_outport_start_work_vt = 1,
  vt_ground_gui_polling_ground_local_outport_start_work_vt = 0,
  invalid_local_port_t = -1
} __po_hi_local_port_t;

#define __PO_HI_NB_DEVICES 0

#define __PO_HI_NB_BUSES 0

#define __PO_HI_NB_PROTOCOLS 0

#define __PO_HI_PORT_TYPE_CONTENT __po_hi_vt_obsw_pulse_nb_ports, __po_hi_vt_obsw_start_work_nb_ports, __po_hi_vt_ground_thrust_update_nb_ports, __po_hi_vt_ground_dheight_nb_ports, __po_hi_vt_ground_gui_polling_ground_nb_ports

#endif
