#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"vt_obsw_pulse_global_outport_thrust_update_vt","vt_obsw_pulse_global_outport_dheight_vt","vt_obsw_start_work_global_inport_artificial_start_work","vt_obsw_start_work_global_outport_thrust_update_vt","vt_obsw_start_work_global_outport_dheight_vt","vt_ground_thrust_update_global_inport_artificial_thrust_update","vt_ground_thrust_update_global_outport_start_work_vt","vt_ground_dheight_global_inport_artificial_dheight","vt_ground_dheight_global_outport_start_work_vt","vt_ground_gui_polling_ground_global_outport_start_work_vt"};

