/* This file was generated automatically - DO NOT MODIFY IT ! */

/* Configuration file used by C_ASN1_Types.h */

#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_NATIVE
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
