/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "taste_socket_control3.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MyReal_Initialize(MyReal* pVal)
{
    *pVal = (MyReal) 0.00000000000000000000E+000;
}
#endif

 
flag MyReal_IsConstraintValid(const MyReal* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (-1.00000000000000000000E+003 <= *pVal && *pVal <= 1.00000000000000000000E+005);
	*pErrCode = ret ? 0 : ERR_MyReal;

	return ret;
}

flag MyReal_Equal(const MyReal* pVal1, const MyReal* pVal2)
{
	flag ret=TRUE;
	
	ret =  *pVal1 == *pVal2 ? TRUE : (*pVal1 == 0.0 ? *pVal2 ==0.0 : (fabs((*pVal1 - *pVal2) / *pVal1) < 0.00001));

	return ret;
}

flag MyReal_Encode(const MyReal* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MyReal_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeReal(pBitStrm, *pVal);
    }

	return ret;
}

flag MyReal_Decode(MyReal* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	BitStream_DecodeReal(pBitStrm, pVal);
	*pErrCode = ret ? 0 : 268435457;

	return ret;
}

flag MyReal_ACN_Encode(const MyReal* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? MyReal_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeReal(pBitStrm, *pVal);
    }

	return ret;
}

flag MyReal_ACN_Decode(MyReal* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    BitStream_DecodeReal(pBitStrm, pVal);
    *pErrCode = ret ? 0 : 268435458;
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MySensorData_Initialize(MySensorData* pVal)
{
    *pVal = (MySensorData) {
    .yawAct = 0.00000000000000000000E+000,
    .pitchAct = 0.00000000000000000000E+000,
    .rollAct = 0.00000000000000000000E+000,
    .baropAct = 0.00000000000000000000E+000,
    .accxAct = 0.00000000000000000000E+000,
    .accyAct = 0.00000000000000000000E+000,
    .acczAct = 0.00000000000000000000E+000
};
}
#endif

 
flag MySensorData_IsConstraintValid(const MySensorData* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = MyReal_IsConstraintValid(&pVal->yawAct, pErrCode);
	if (ret) {
	    ret = MyReal_IsConstraintValid(&pVal->pitchAct, pErrCode);
	    if (ret) {
	        ret = MyReal_IsConstraintValid(&pVal->rollAct, pErrCode);
	        if (ret) {
	            ret = MyReal_IsConstraintValid(&pVal->baropAct, pErrCode);
	            if (ret) {
	                ret = MyReal_IsConstraintValid(&pVal->accxAct, pErrCode);
	                if (ret) {
	                    ret = MyReal_IsConstraintValid(&pVal->accyAct, pErrCode);
	                    if (ret) {
	                        ret = MyReal_IsConstraintValid(&pVal->acczAct, pErrCode);
	                    
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag MySensorData_Equal(const MySensorData* pVal1, const MySensorData* pVal2)
{
	flag ret=TRUE;
	
	ret = MyReal_Equal(&pVal1->yawAct, &pVal2->yawAct);
	if (ret) {
	    ret = MyReal_Equal(&pVal1->pitchAct, &pVal2->pitchAct);
	    if (ret) {
	        ret = MyReal_Equal(&pVal1->rollAct, &pVal2->rollAct);
	        if (ret) {
	            ret = MyReal_Equal(&pVal1->baropAct, &pVal2->baropAct);
	            if (ret) {
	                ret = MyReal_Equal(&pVal1->accxAct, &pVal2->accxAct);
	                if (ret) {
	                    ret = MyReal_Equal(&pVal1->accyAct, &pVal2->accyAct);
	                    if (ret) {
	                        ret = MyReal_Equal(&pVal1->acczAct, &pVal2->acczAct);
	                    
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

flag MySensorData_Encode(const MySensorData* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MySensorData_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode yawAct */
	    ret = MyReal_Encode(&pVal->yawAct, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode pitchAct */
	        ret = MyReal_Encode(&pVal->pitchAct, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode rollAct */
	            ret = MyReal_Encode(&pVal->rollAct, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode baropAct */
	                ret = MyReal_Encode(&pVal->baropAct, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode accxAct */
	                    ret = MyReal_Encode(&pVal->accxAct, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode accyAct */
	                        ret = MyReal_Encode(&pVal->accyAct, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode acczAct */
	                            ret = MyReal_Encode(&pVal->acczAct, pBitStrm, pErrCode, FALSE);
	                        
	                        }
	                    }
	                }
	            }
	        }
	    }
    }

	return ret;
}

flag MySensorData_Decode(MySensorData* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode yawAct */
	ret = MyReal_Decode(&pVal->yawAct, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode pitchAct */
	    ret = MyReal_Decode(&pVal->pitchAct, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode rollAct */
	        ret = MyReal_Decode(&pVal->rollAct, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode baropAct */
	            ret = MyReal_Decode(&pVal->baropAct, pBitStrm, pErrCode);
	            if (ret) {
	                /*Decode accxAct */
	                ret = MyReal_Decode(&pVal->accxAct, pBitStrm, pErrCode);
	                if (ret) {
	                    /*Decode accyAct */
	                    ret = MyReal_Decode(&pVal->accyAct, pBitStrm, pErrCode);
	                    if (ret) {
	                        /*Decode acczAct */
	                        ret = MyReal_Decode(&pVal->acczAct, pBitStrm, pErrCode);
	                    
	                    }
	                }
	            }
	        }
	    }
	}


	return ret;
}

flag MySensorData_ACN_Encode(const MySensorData* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? MySensorData_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode yawAct */
	    ret = MyReal_ACN_Encode(&pVal->yawAct, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode pitchAct */
	        ret = MyReal_ACN_Encode(&pVal->pitchAct, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode rollAct */
	            ret = MyReal_ACN_Encode(&pVal->rollAct, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode baropAct */
	                ret = MyReal_ACN_Encode(&pVal->baropAct, pBitStrm, pErrCode, FALSE);
	                if (ret) {
	                    /*Encode accxAct */
	                    ret = MyReal_ACN_Encode(&pVal->accxAct, pBitStrm, pErrCode, FALSE);
	                    if (ret) {
	                        /*Encode accyAct */
	                        ret = MyReal_ACN_Encode(&pVal->accyAct, pBitStrm, pErrCode, FALSE);
	                        if (ret) {
	                            /*Encode acczAct */
	                            ret = MyReal_ACN_Encode(&pVal->acczAct, pBitStrm, pErrCode, FALSE);

	                        }

	                    }

	                }

	            }

	        }

	    }

    }

	return ret;
}

flag MySensorData_ACN_Decode(MySensorData* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode yawAct */
    ret = MyReal_ACN_Decode(&pVal->yawAct, pBitStrm, pErrCode);
    if (ret) {
        /*Decode pitchAct */
        ret = MyReal_ACN_Decode(&pVal->pitchAct, pBitStrm, pErrCode);
        if (ret) {
            /*Decode rollAct */
            ret = MyReal_ACN_Decode(&pVal->rollAct, pBitStrm, pErrCode);
            if (ret) {
                /*Decode baropAct */
                ret = MyReal_ACN_Decode(&pVal->baropAct, pBitStrm, pErrCode);
                if (ret) {
                    /*Decode accxAct */
                    ret = MyReal_ACN_Decode(&pVal->accxAct, pBitStrm, pErrCode);
                    if (ret) {
                        /*Decode accyAct */
                        ret = MyReal_ACN_Decode(&pVal->accyAct, pBitStrm, pErrCode);
                        if (ret) {
                            /*Decode acczAct */
                            ret = MyReal_ACN_Decode(&pVal->acczAct, pBitStrm, pErrCode);

                        }

                    }

                }

            }

        }

    }


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MyDroneData_Initialize(MyDroneData* pVal)
{
    *pVal = (MyDroneData) {
    .yawrateRef = 0.00000000000000000000E+000,
    .pitchRef = 0.00000000000000000000E+000,
    .rollRef = 0.00000000000000000000E+000,
    .thrustRef = 0.00000000000000000000E+000
};
}
#endif

 
flag MyDroneData_IsConstraintValid(const MyDroneData* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = MyReal_IsConstraintValid(&pVal->yawrateRef, pErrCode);
	if (ret) {
	    ret = MyReal_IsConstraintValid(&pVal->pitchRef, pErrCode);
	    if (ret) {
	        ret = MyReal_IsConstraintValid(&pVal->rollRef, pErrCode);
	        if (ret) {
	            ret = MyReal_IsConstraintValid(&pVal->thrustRef, pErrCode);
	        
	        }
	    }
	}

	return ret;
}

flag MyDroneData_Equal(const MyDroneData* pVal1, const MyDroneData* pVal2)
{
	flag ret=TRUE;
	
	ret = MyReal_Equal(&pVal1->yawrateRef, &pVal2->yawrateRef);
	if (ret) {
	    ret = MyReal_Equal(&pVal1->pitchRef, &pVal2->pitchRef);
	    if (ret) {
	        ret = MyReal_Equal(&pVal1->rollRef, &pVal2->rollRef);
	        if (ret) {
	            ret = MyReal_Equal(&pVal1->thrustRef, &pVal2->thrustRef);
	        
	        }
	    }
	}

	return ret;
}

flag MyDroneData_Encode(const MyDroneData* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MyDroneData_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode yawrateRef */
	    ret = MyReal_Encode(&pVal->yawrateRef, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode pitchRef */
	        ret = MyReal_Encode(&pVal->pitchRef, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode rollRef */
	            ret = MyReal_Encode(&pVal->rollRef, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode thrustRef */
	                ret = MyReal_Encode(&pVal->thrustRef, pBitStrm, pErrCode, FALSE);
	            
	            }
	        }
	    }
    }

	return ret;
}

flag MyDroneData_Decode(MyDroneData* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode yawrateRef */
	ret = MyReal_Decode(&pVal->yawrateRef, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode pitchRef */
	    ret = MyReal_Decode(&pVal->pitchRef, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode rollRef */
	        ret = MyReal_Decode(&pVal->rollRef, pBitStrm, pErrCode);
	        if (ret) {
	            /*Decode thrustRef */
	            ret = MyReal_Decode(&pVal->thrustRef, pBitStrm, pErrCode);
	        
	        }
	    }
	}


	return ret;
}

flag MyDroneData_ACN_Encode(const MyDroneData* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? MyDroneData_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode yawrateRef */
	    ret = MyReal_ACN_Encode(&pVal->yawrateRef, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode pitchRef */
	        ret = MyReal_ACN_Encode(&pVal->pitchRef, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode rollRef */
	            ret = MyReal_ACN_Encode(&pVal->rollRef, pBitStrm, pErrCode, FALSE);
	            if (ret) {
	                /*Encode thrustRef */
	                ret = MyReal_ACN_Encode(&pVal->thrustRef, pBitStrm, pErrCode, FALSE);

	            }

	        }

	    }

    }

	return ret;
}

flag MyDroneData_ACN_Decode(MyDroneData* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode yawrateRef */
    ret = MyReal_ACN_Decode(&pVal->yawrateRef, pBitStrm, pErrCode);
    if (ret) {
        /*Decode pitchRef */
        ret = MyReal_ACN_Decode(&pVal->pitchRef, pBitStrm, pErrCode);
        if (ret) {
            /*Decode rollRef */
            ret = MyReal_ACN_Decode(&pVal->rollRef, pBitStrm, pErrCode);
            if (ret) {
                /*Decode thrustRef */
                ret = MyReal_ACN_Decode(&pVal->thrustRef, pBitStrm, pErrCode);

            }

        }

    }


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MyBool_Initialize(MyBool* pVal)
{
    *pVal = (MyBool) FALSE;
}
#endif

 
flag MyBool_IsConstraintValid(const MyBool* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;

	return ret;
}

flag MyBool_Equal(const MyBool* pVal1, const MyBool* pVal2)
{
	flag ret=TRUE;
	
	ret = ( (*pVal1 && *pVal2) || (!*pVal1 && !*pVal2));

	return ret;
}

flag MyBool_Encode(const MyBool* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MyBool_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_AppendBit(pBitStrm,*pVal);
    }

	return ret;
}

flag MyBool_Decode(MyBool* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : 268435459;

	return ret;
}

flag MyBool_ACN_Encode(const MyBool* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? MyBool_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    {
	    	static byte true_data[] = {0x80};
	    	static byte false_data[] = {0x7F};
	        byte* tmp = *pVal ? true_data : false_data; 
	        BitStream_AppendBits(pBitStrm, tmp, 1);
	    }
    }

	return ret;
}

flag MyBool_ACN_Decode(MyBool* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    {
    	static byte tmp[] = {0x80};
    	ret = BitStream_ReadBitPattern(pBitStrm, tmp, 1, pVal);
        *pErrCode = ret ? 0 : 268435460;
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MyEnum_Initialize(MyEnum* pVal)
{
    *pVal = (MyEnum) hello;
}
#endif

 
flag MyEnum_IsConstraintValid(const MyEnum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (((*pVal == hello) || (*pVal == world)) || (*pVal == howareyou));
	*pErrCode = ret ? 0 : ERR_MyEnum;

	return ret;
}

flag MyEnum_Equal(const MyEnum* pVal1, const MyEnum* pVal2)
{
	flag ret=TRUE;
	
	ret = (*pVal1 == *pVal2);

	return ret;
}

flag MyEnum_Encode(const MyEnum* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MyEnum_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) 
	    {
	        case hello:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	        	break;
	        case world:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	        	break;
	        case howareyou:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	        	break;
	        default:
	    	    *pErrCode = 1073741825; //COVERAGE_IGNORE
	    	    ret = FALSE;            //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag MyEnum_Decode(MyEnum* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint enumIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 2);
	*pErrCode = ret ? 0 : 268435461;
	if (ret) {
	    switch(enumIndex) 
	    {
	        case 0: 
	            *pVal = hello;
	            break;
	        case 1: 
	            *pVal = world;
	            break;
	        case 2: 
	            *pVal = howareyou;
	            break;
	        default:
		        *pErrCode = 1073741826;     //COVERAGE_IGNORE
		        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}

flag MyEnum_ACN_Encode(const MyEnum* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;

    ret = bCheckConstraints ? MyEnum_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) { 
	        case hello:
	            intVal = 0;
	            break;
	        case world:
	            intVal = 1;
	            break;
	        case howareyou:
	            intVal = 2;
	            break;
	        default:
	            ret = FALSE;                            //COVERAGE_IGNORE
	            *pErrCode = 1073741827;      //COVERAGE_IGNORE
	    }
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal, 0, 2);
    }

	return ret;
}

flag MyEnum_ACN_Decode(MyEnum* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;
    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, &intVal, 0, 2);
    *pErrCode = ret ? 0 : 268435462;
    if (ret) {
        switch (intVal) {
            case 0:
                *pVal = hello;
                break;
            case 1:
                *pVal = world;
                break;
            case 2:
                *pVal = howareyou;
                break;
        default:
            ret = FALSE;                            //COVERAGE_IGNORE
            *pErrCode = 1073741828;      //COVERAGE_IGNORE
        };
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MySeqOf_Initialize(MySeqOf* pVal)
{
    *pVal = (MySeqOf) {    .arr = 
    {
        hello        
    }
};
}
#endif

 
flag MySeqOf_IsConstraintValid(const MySeqOf* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;
	i1 = 0;
	while (ret && (i1< 2)) {
	    ret = MyEnum_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}

flag MySeqOf_Equal(const MySeqOf* pVal1, const MySeqOf* pVal2)
{
	flag ret=TRUE;
	int i1=0;
	
	for(i1 = 0; ret && i1<2; i1++) 
	{
		ret = MyEnum_Equal(&pVal1->arr[i1], &pVal2->arr[i1]);
	}

	return ret;
}

flag MySeqOf_Encode(const MySeqOf* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? MySeqOf_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    	
	    for(i1=0; (i1 < (int)2) && ret; i1++) 
	    {
	    	ret = MyEnum_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag MySeqOf_Decode(MySeqOf* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	int i1=0;

		
	for(i1=0; (i1 < (int)2) && ret; i1++) 
	{
		ret = MyEnum_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
	}

	return ret;
}

flag MySeqOf_ACN_Encode(const MySeqOf* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? MySeqOf_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    	
	    for(i1=0; (i1 < (int)2) && ret; i1++) 
	    {
	    	ret = MyEnum_ACN_Encode(&pVal->arr[i1], pBitStrm, pErrCode, FALSE);
	    }
    }

	return ret;
}

flag MySeqOf_ACN_Decode(MySeqOf* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    	
    for(i1=0; (i1 < (int)2) && ret; i1++) 
    {
    	ret = MyEnum_ACN_Decode(&pVal->arr[i1], pBitStrm, pErrCode);
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MyOctStr_Initialize(MyOctStr* pVal)
{
    *pVal = (MyOctStr) {
    {
        0x00
    }
};
}
#endif

 
flag MyOctStr_IsConstraintValid(const MyOctStr* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (3 == 3);
	*pErrCode = ret ? 0 : ERR_MyOctStr;

	return ret;
}

flag MyOctStr_Equal(const MyOctStr* pVal1, const MyOctStr* pVal2)
{
	flag ret=TRUE;
	
	ret = (memcmp(pVal1->arr, pVal2->arr, 3) ==0);
		

	return ret;
}

flag MyOctStr_Encode(const MyOctStr* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	int i1=0;
    
	ret = bCheckConstraints ? MyOctStr_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    	
	    for(i1=0; (i1 < (int)3) && ret; i1++) 
	    {
	    	BitStream_AppendByte0(pBitStrm, pVal->arr[i1]);
	    }
    }

	return ret;
}

flag MyOctStr_Decode(MyOctStr* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	int i1=0;

		
	for(i1=0; (i1 < (int)3) && ret; i1++) 
	{
		ret = BitStream_ReadByte(pBitStrm, &pVal->arr[i1]); 
		*pErrCode = ret ? 0 : 268435463;
	}

	return ret;
}

flag MyOctStr_ACN_Encode(const MyOctStr* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    int i1=0;

    ret = bCheckConstraints ? MyOctStr_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    	
	    for(i1=0; (i1 < (int)3) && ret; i1++) 
	    {
	    	BitStream_AppendByte0(pBitStrm, pVal->arr[i1]);
	    }
    }

	return ret;
}

flag MyOctStr_ACN_Decode(MyOctStr* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    int i1=0;
    	
    for(i1=0; (i1 < (int)3) && ret; i1++) 
    {
    	ret = BitStream_ReadByte(pBitStrm, &pVal->arr[i1]); 
    	*pErrCode = ret ? 0 : 268435464;
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MySeq_validity_Initialize(MySeq_validity* pVal)
{
    *pVal = (MySeq_validity) valid;
}
#endif

 
flag MySeq_validity_IsConstraintValid(const MySeq_validity* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((*pVal == valid) || (*pVal == invalid));
	*pErrCode = ret ? 0 : ERR_MySeq_validity;

	return ret;
}

flag MySeq_validity_Equal(const MySeq_validity* pVal1, const MySeq_validity* pVal2)
{
	flag ret=TRUE;
	
	ret = (*pVal1 == *pVal2);

	return ret;
}

flag MySeq_validity_Encode(const MySeq_validity* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MySeq_validity_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) 
	    {
	        case valid:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	        	break;
	        case invalid:   
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	        	break;
	        default:
	    	    *pErrCode = 1073741829; //COVERAGE_IGNORE
	    	    ret = FALSE;            //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag MySeq_validity_Decode(MySeq_validity* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint enumIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 1);
	*pErrCode = ret ? 0 : 268435465;
	if (ret) {
	    switch(enumIndex) 
	    {
	        case 0: 
	            *pVal = valid;
	            break;
	        case 1: 
	            *pVal = invalid;
	            break;
	        default:
		        *pErrCode = 1073741830;     //COVERAGE_IGNORE
		        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}

flag MySeq_validity_ACN_Encode(const MySeq_validity* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;

    ret = bCheckConstraints ? MySeq_validity_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(*pVal) { 
	        case valid:
	            intVal = 0;
	            break;
	        case invalid:
	            intVal = 1;
	            break;
	        default:
	            ret = FALSE;                            //COVERAGE_IGNORE
	            *pErrCode = 1073741831;      //COVERAGE_IGNORE
	    }
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal, 0, 1);
    }

	return ret;
}

flag MySeq_validity_ACN_Decode(MySeq_validity* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    asn1SccUint intVal = 0;
    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, &intVal, 0, 1);
    *pErrCode = ret ? 0 : 268435466;
    if (ret) {
        switch (intVal) {
            case 0:
                *pVal = valid;
                break;
            case 1:
                *pVal = invalid;
                break;
        default:
            ret = FALSE;                            //COVERAGE_IGNORE
            *pErrCode = 1073741832;      //COVERAGE_IGNORE
        };
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void T_Int32_Initialize(T_Int32* pVal)
{
    *pVal = (T_Int32) -2147483648LL;
}
#endif

 
flag T_Int32_IsConstraintValid(const T_Int32* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (-2147483648LL <= *pVal && *pVal <= 2147483647LL);
	*pErrCode = ret ? 0 : ERR_T_Int32;

	return ret;
}

flag T_Int32_Equal(const T_Int32* pVal1, const T_Int32* pVal2)
{
	flag ret=TRUE;
	
	ret = (*pVal1 == *pVal2);

	return ret;
}

flag T_Int32_Encode(const T_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? T_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, *pVal, -2147483648LL, 2147483647LL);
    }

	return ret;
}

flag T_Int32_Decode(T_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : 268435467;

	return ret;
}

flag T_Int32_ACN_Encode(const T_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? T_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, *pVal, -2147483648LL, 2147483647LL);
    }

	return ret;
}

flag T_Int32_ACN_Decode(T_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
    *pErrCode = ret ? 0 : 268435468;
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void T_UInt32_Initialize(T_UInt32* pVal)
{
    *pVal = (T_UInt32) 0;
}
#endif

 
flag T_UInt32_IsConstraintValid(const T_UInt32* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_T_UInt32;

	return ret;
}

flag T_UInt32_Equal(const T_UInt32* pVal1, const T_UInt32* pVal2)
{
	flag ret=TRUE;
	
	ret = (*pVal1 == *pVal2);

	return ret;
}

flag T_UInt32_Encode(const T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? T_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag T_UInt32_Decode(T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : 268435469;

	return ret;
}

flag T_UInt32_ACN_Encode(const T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? T_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 4294967295LL);
    }

	return ret;
}

flag T_UInt32_ACN_Decode(T_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
    *pErrCode = ret ? 0 : 268435470;
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void T_Int8_Initialize(T_Int8* pVal)
{
    *pVal = (T_Int8) -128;
}
#endif

 
flag T_Int8_IsConstraintValid(const T_Int8* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (-128 <= *pVal && *pVal <= 127);
	*pErrCode = ret ? 0 : ERR_T_Int8;

	return ret;
}

flag T_Int8_Equal(const T_Int8* pVal1, const T_Int8* pVal2)
{
	flag ret=TRUE;
	
	ret = (*pVal1 == *pVal2);

	return ret;
}

flag T_Int8_Encode(const T_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? T_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, *pVal, -128, 127);
    }

	return ret;
}

flag T_Int8_Decode(T_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
	*pErrCode = ret ? 0 : 268435471;

	return ret;
}

flag T_Int8_ACN_Encode(const T_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? T_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, *pVal, -128, 127);
    }

	return ret;
}

flag T_Int8_ACN_Decode(T_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
    *pErrCode = ret ? 0 : 268435472;
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void T_UInt8_Initialize(T_UInt8* pVal)
{
    *pVal = (T_UInt8) 0;
}
#endif

 
flag T_UInt8_IsConstraintValid(const T_UInt8* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 255);
	*pErrCode = ret ? 0 : ERR_T_UInt8;

	return ret;
}

flag T_UInt8_Equal(const T_UInt8* pVal1, const T_UInt8* pVal2)
{
	flag ret=TRUE;
	
	ret = (*pVal1 == *pVal2);

	return ret;
}

flag T_UInt8_Encode(const T_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? T_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 255);
    }

	return ret;
}

flag T_UInt8_Decode(T_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
	*pErrCode = ret ? 0 : 268435473;

	return ret;
}

flag T_UInt8_ACN_Encode(const T_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? T_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, *pVal, 0, 255);
    }

	return ret;
}

flag T_UInt8_ACN_Decode(T_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
    *pErrCode = ret ? 0 : 268435474;
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MyInteger_Initialize(MyInteger* pVal)
{
    *pVal = (MyInteger) 0;
}
#endif

 
flag MyInteger_IsConstraintValid(const MyInteger* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = T_UInt8_IsConstraintValid(pVal, pErrCode);

	return ret;
}

flag MyInteger_Equal(const MyInteger* pVal1, const MyInteger* pVal2)
{
	flag ret=TRUE;
	
	ret = T_UInt8_Equal(pVal1, pVal2);

	return ret;
}

flag MyInteger_Encode(const MyInteger* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MyInteger_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = T_UInt8_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag MyInteger_Decode(MyInteger* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = T_UInt8_Decode(pVal, pBitStrm, pErrCode);

	return ret;
}

flag MyInteger_ACN_Encode(const MyInteger* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? MyInteger_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    ret = T_UInt8_ACN_Encode(pVal, pBitStrm, pErrCode, FALSE);
    }

	return ret;
}

flag MyInteger_ACN_Decode(MyInteger* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    ret = T_UInt8_ACN_Decode(pVal, pBitStrm, pErrCode);
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MySeq_Initialize(MySeq* pVal)
{
    *pVal = (MySeq) {
    .input_data = 0,
    .output_data = 0,
    .validity = valid
};
}
#endif

 
flag MySeq_IsConstraintValid(const MySeq* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = MyInteger_IsConstraintValid(&pVal->input_data, pErrCode);
	if (ret) {
	    ret = MyInteger_IsConstraintValid(&pVal->output_data, pErrCode);
	    if (ret) {
	        ret = MySeq_validity_IsConstraintValid(&pVal->validity, pErrCode);
	    
	    }
	}

	return ret;
}

flag MySeq_Equal(const MySeq* pVal1, const MySeq* pVal2)
{
	flag ret=TRUE;
	
	ret = MyInteger_Equal(&pVal1->input_data, &pVal2->input_data);
	if (ret) {
	    ret = MyInteger_Equal(&pVal1->output_data, &pVal2->output_data);
	    if (ret) {
	        ret = MySeq_validity_Equal(&pVal1->validity, &pVal2->validity);
	    
	    }
	}

	return ret;
}

flag MySeq_Encode(const MySeq* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MySeq_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode input_data */
	    ret = MyInteger_Encode(&pVal->input_data, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode output_data */
	        ret = MyInteger_Encode(&pVal->output_data, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode validity */
	            ret = MySeq_validity_Encode(&pVal->validity, pBitStrm, pErrCode, FALSE);
	        
	        }
	    }
    }

	return ret;
}

flag MySeq_Decode(MySeq* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	/*Decode input_data */
	ret = MyInteger_Decode(&pVal->input_data, pBitStrm, pErrCode);
	if (ret) {
	    /*Decode output_data */
	    ret = MyInteger_Decode(&pVal->output_data, pBitStrm, pErrCode);
	    if (ret) {
	        /*Decode validity */
	        ret = MySeq_validity_Decode(&pVal->validity, pBitStrm, pErrCode);
	    
	    }
	}


	return ret;
}

flag MySeq_ACN_Encode(const MySeq* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? MySeq_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    /*Encode input_data */
	    ret = MyInteger_ACN_Encode(&pVal->input_data, pBitStrm, pErrCode, FALSE);
	    if (ret) {
	        /*Encode output_data */
	        ret = MyInteger_ACN_Encode(&pVal->output_data, pBitStrm, pErrCode, FALSE);
	        if (ret) {
	            /*Encode validity */
	            ret = MySeq_validity_ACN_Encode(&pVal->validity, pBitStrm, pErrCode, FALSE);

	        }

	    }

    }

	return ret;
}

flag MySeq_ACN_Decode(MySeq* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    *pErrCode = 0;
    /*Decode input_data */
    ret = MyInteger_ACN_Decode(&pVal->input_data, pBitStrm, pErrCode);
    if (ret) {
        /*Decode output_data */
        ret = MyInteger_ACN_Decode(&pVal->output_data, pBitStrm, pErrCode);
        if (ret) {
            /*Decode validity */
            ret = MySeq_validity_ACN_Decode(&pVal->validity, pBitStrm, pErrCode);

        }

    }


    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void MyChoice_Initialize(MyChoice* pVal)
{
    *pVal = (MyChoice) {
    .kind = a_PRESENT,
    .u = { .a = FALSE}
};
}
#endif

 
flag MyChoice_IsConstraintValid(const MyChoice* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	switch (pVal->kind) {
	    case a_PRESENT :
	        ret = TRUE; *pErrCode = 0;
	        break;
	    case b_PRESENT :
	        ret = MySeq_IsConstraintValid(&pVal->u.b, pErrCode);
	        break;
	    default:
		    *pErrCode = 805306369;   //COVERAGE_IGNORE
		    ret = FALSE;                    //COVERAGE_IGNORE
	}

	return ret;
}

flag MyChoice_Equal(const MyChoice* pVal1, const MyChoice* pVal2)
{
	flag ret=TRUE;
	
	ret = (pVal1->kind == pVal2->kind);
	if (ret) {
		switch(pVal1->kind) 
		{
		case a_PRESENT:
			ret = ( (pVal1->u.a && pVal2->u.a) || (!pVal1->u.a && !pVal2->u.a));
			break;
		case b_PRESENT:
			ret = MySeq_Equal(&pVal1->u.b, &pVal2->u.b);
			break;
		default:
			ret = FALSE;    //COVERAGE_IGNORE
		}
	}

	return ret;
}

flag MyChoice_Encode(const MyChoice* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? MyChoice_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(pVal->kind) 
	    {
	    case a_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	    	BitStream_AppendBit(pBitStrm,pVal->u.a);
	    	break;
	    case b_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	    	ret = MySeq_Encode(&pVal->u.b, pBitStrm, pErrCode, FALSE);
	    	break;
	    default:
	        *pErrCode = 805306370;         //COVERAGE_IGNORE
	        ret = FALSE;                    //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag MyChoice_Decode(MyChoice* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	asn1SccSint nChoiceIndex;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nChoiceIndex, 0, 1);
	*pErrCode = ret ? 0 : 268435475;
	if (ret) {
	    switch(nChoiceIndex) 
	    {
	    case 0:
	    	pVal->kind = a_PRESENT;
	    	ret = BitStream_ReadBit(pBitStrm, &pVal->u.a);
	    	*pErrCode = ret ? 0 : 268435476;
	    	break;
	    case 1:
	    	pVal->kind = b_PRESENT;
	    	ret = MySeq_Decode(&pVal->u.b, pBitStrm, pErrCode);
	    	break;
	    default:
	        *pErrCode = 805306371;     //COVERAGE_IGNORE
	        ret = FALSE;                //COVERAGE_IGNORE
	    }
	}

	return ret;
}

flag MyChoice_ACN_Encode(const MyChoice* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? MyChoice_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    switch(pVal->kind) 
	    {
	    case a_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 1);
	    	{
	    		static byte true_data[] = {0x80};
	    		static byte false_data[] = {0x7F};
	    	    byte* tmp = pVal->u.a ? true_data : false_data; 
	    	    BitStream_AppendBits(pBitStrm, tmp, 1);
	    	}
	    	break;
	    case b_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 1);
	    	ret = MySeq_ACN_Encode(&pVal->u.b, pBitStrm, pErrCode, FALSE);
	    	break;
	    default:
	        *pErrCode = 805306372;         //COVERAGE_IGNORE
	        ret = FALSE;                    //COVERAGE_IGNORE
	    }
    }

	return ret;
}

flag MyChoice_ACN_Decode(MyChoice* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    asn1SccSint nChoiceIndex;
    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &nChoiceIndex, 0, 1);
    *pErrCode = ret ? 0 : 268435477;
    if (ret) {
        switch(nChoiceIndex) 
        {
        case 0:
        	pVal->kind = a_PRESENT;
        	{
        		static byte tmp[] = {0x80};
        		ret = BitStream_ReadBitPattern(pBitStrm, tmp, 1, &pVal->u.a);
        	    *pErrCode = ret ? 0 : 268435478;
        	}
        	break;
        case 1:
        	pVal->kind = b_PRESENT;
        	ret = MySeq_ACN_Decode(&pVal->u.b, pBitStrm, pErrCode);
        	break;
        default:
            *pErrCode = 805306373;     //COVERAGE_IGNORE
            ret = FALSE;                //COVERAGE_IGNORE
        }
    }
    return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void T_Boolean_Initialize(T_Boolean* pVal)
{
    *pVal = (T_Boolean) FALSE;
}
#endif

 
flag T_Boolean_IsConstraintValid(const T_Boolean* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;

	return ret;
}

flag T_Boolean_Equal(const T_Boolean* pVal1, const T_Boolean* pVal2)
{
	flag ret=TRUE;
	
	ret = ( (*pVal1 && *pVal2) || (!*pVal1 && !*pVal2));

	return ret;
}

flag T_Boolean_Encode(const T_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
    
	ret = bCheckConstraints ? T_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    BitStream_AppendBit(pBitStrm,*pVal);
    }

	return ret;
}

flag T_Boolean_Decode(T_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;

	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : 268435479;

	return ret;
}

flag T_Boolean_ACN_Encode(const T_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    ret = bCheckConstraints ? T_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret) {
	    {
	    	static byte true_data[] = {0x80};
	    	static byte false_data[] = {0x7F};
	        byte* tmp = *pVal ? true_data : false_data; 
	        BitStream_AppendBits(pBitStrm, tmp, 1);
	    }
    }

	return ret;
}

flag T_Boolean_ACN_Decode(T_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
    {
    	static byte tmp[] = {0x80};
    	ret = BitStream_ReadBitPattern(pBitStrm, tmp, 1, pVal);
        *pErrCode = ret ? 0 : 268435480;
    }
    return ret;
}

const MySeqOf myVar = {    .arr = 
    {
        hello,
        world        
    }
};
