/* This file was generated automatically - DO NOT MODIFY IT ! */

/* Configuration file used by C_ASN1_Types.h */

#define __NEED_MyInteger_NATIVE
#define __NEED_WorldData_UPER
#define __NEED_WorldData_NATIVE
#define __NEED_MyInteger_UPER
#define __NEED_MyInteger_UPER
#define __NEED_WorldData_UPER
#define __NEED_SafetyEvent_UPER
#define __NEED_WorldData_UPER
#define __NEED_SafetyEvent_UPER
#define __NEED_Trajectory_UPER
#define __NEED_Trajectory_UPER
#define __NEED_WorldData_UPER
#define __NEED_MyInteger_UPER
#define __NEED_WorldData_NATIVE
#define __NEED_MyInteger_NATIVE
#define __NEED_PixyData_UPER
#define __NEED_MyInteger_UPER
#define __NEED_DroneSensorData_UPER
#define __NEED_Agent_UPER
#define __NEED_DroneSensorData_UPER
#define __NEED_Agent_UPER
#define __NEED_MyInteger_UPER
#define __NEED_DroneControllerInput_UPER
#define __NEED_DroneControllerInput_UPER
#define __NEED_DroneControllerInput_UPER
#define __NEED_PixyData_UPER
#define __NEED_Agent_UPER
#define __NEED_DroneSensorData_UPER
#define __NEED_Agent_UPER
#define __NEED_PixyData_UPER
#define __NEED_MyInteger_UPER
#define __NEED_Agent_UPER
#define __NEED_PixyData_UPER
#define __NEED_Agent_UPER
#define __NEED_WorldData_UPER
#define __NEED_SafetyEvent_UPER
#define __NEED_WorldData_UPER
#define __NEED_SafetyEvent_UPER
#define __NEED_Trajectory_UPER
#define __NEED_Trajectory_UPER
#define __NEED_WorldData_UPER
#define __NEED_DroneControllerInput_UPER
#define __NEED_Trajectory_UPER
#define __NEED_WorldData_UPER
#define __NEED_Trajectory_UPER
#define __NEED_WorldData_UPER
#define __NEED_DroneControllerInput_UPER
#define __NEED_DroneControllerInput_UPER
#define __NEED_Agent_UPER
#define __NEED_Agent_UPER
#define __NEED_DroneControllerInput_UPER
#define __NEED_WorldData_UPER
#define __NEED_DroneControllerInput_UPER
#define __NEED_DroneSensorData_UPER
